#!/bin/bash

shopt -s nocasematch

cd $(dirname $0)

AGENT="$1"
shift

if [ "$AGENT" = "coordinator" ]; then
	AGENT_MODULE="coordinator"
	AGENT_PORT=8050
	AGENT_PORT_RANGE=8050-8058
	echo "Preparing agent image..."
	docker build -q -t "$AGENT" -f ../docker/Dockerfile_coordinator.demo .. || exit 1

elif [ "$AGENT" = "hospital1" ]; then
	AGENT_MODULE="hospital1"
	AGENT_PORT=8070
	AGENT_PORT_RANGE=8070-8078
	echo "Preparing agent image..."
	docker build -q -t "$AGENT" -f ../docker/Dockerfile_hospital.demo --build-arg hospital_name="$AGENT" .. || exit 1

elif [ "$AGENT" = "hospital2" ]; then
	AGENT_MODULE="hospital2"
	AGENT_PORT=8090
	AGENT_PORT_RANGE=8090-8098
	echo "Preparing agent image..."
	docker build -q -t "$AGENT" -f ../docker/Dockerfile_hospital.demo --build-arg hospital_name="$AGENT" .. || exit 1

elif [ "$AGENT" = "nhsheadoffice" ]; then
	AGENT_MODULE="nhsheadoffice"
	AGENT_PORT=8080
	AGENT_PORT_RANGE=8080-8088
	echo "Preparing agent image..."
	docker build -q -t "$AGENT" -f ../docker/Dockerfile.demo .. || exit 1

elif [ "$AGENT" = "regulator" ]; then
	AGENT_MODULE="regulator"
	AGENT_PORT=8100
	AGENT_PORT_RANGE=8100-8108
	echo "Preparing agent image..."
	docker build -q -t "$AGENT" -f ../docker/Dockerfile.demo .. || exit 1
elif [ "$AGENT" = "hospital3" ]; then
	AGENT_MODULE="hospital3"
	AGENT_PORT=8110
	AGENT_PORT_RANGE=8110-8118
	docker build -q -t "$AGENT" -f ../docker/Dockerfile.demo .. || exit 1
elif [ "$AGENT" = "coordinator_server" ]; then
	AGENT_MODULE="coordinator_server"
	AGENT_PORT=8130
	AGENT_PORT_RANGE=8130-8140
	docker build -q -t "$AGENT" -f ../docker/Dockerfile.demo .. || exit 1
elif [ "$AGENT" = "hospital1_web" ]; then
	AGENT_MODULE="hospital1_web"
	AGENT_PORT=8160
	AGENT_PORT_RANGE=8160-8170
	docker build -q -t "$AGENT" -f ../docker/Dockerfile.demo .. || exit 1
else
	echo "Please specify which agent you want to run. Choose from 'coordinator', 'hospital1', 'hospital2', 'hospital3', 'nhsheadoffice' or 'regulator'."
	exit 1
fi

if [ -z "${PWD_HOST_FQDN}" ]; then
	DOCKERHOST=`docker run --rm --net=host codenvy/che-ip`
    export RUNMODE="docker"
else
	PWD_HOST="${PWD_HOST_FQDN}"
    if [ "$PWD_HOST_FQDN" = "labs.play-with-docker.com" ]
      then
        export ETH_CONFIG="eth1"
      elif [ "$PWD_HOST_FQDN" = "play-with-docker.vonx.io" ]
      then
        export ETH_CONFIG="eth0"
      else
        export ETH_CONFIG="eth0"
      fi
    MY_HOST=`ifconfig ${ETH_CONFIG} | grep inet | cut -d':' -f2 | cut -d' ' -f1 | sed 's/\./\-/g'`
    export DOCKERHOST="ip${MY_HOST}-${SESSION_ID}-{PORT}.direct.${PWD_HOST_FQDN}"
    export RUNMODE="pwd"
fi

echo $DOCKERHOST

LEDGER_URL=http://dev.bcovrin.vonx.io
DOCKER_ENV="-e LOG_LEVEL=${LOG_LEVEL} -e RUNMODE=${RUNMODE} -e DOCKERHOST=${DOCKERHOST}"
if ! [ -z "$POSTGRES" ]; then
	DOCKER_ENV="${DOCKER_ENV} -e POSTGRES=1 -e RUST_BACKTRACE=1"
fi
if ! [ -z "$LEDGER_URL" ]; then
	GENESIS_URL="${LEDGER_URL}/genesis"
	DOCKER_ENV="${DOCKER_ENV} -e LEDGER_URL=${LEDGER_URL} -e GENESIS_URL=${GENESIS_URL}"
fi

if ! [ -z "$LEDGER" ]; then
	DOCKER_ENV="${DOCKER_ENV} -e LEDGER=${LEDGER}"
fi

# on Windows, docker run needs to be prefixed by winpty
if [ "$OSTYPE" = "msys" ]; then
	DOCKER="winpty docker"
fi
DOCKER=${DOCKER:-docker}

echo "Starting $AGENT..."
$DOCKER run --name $AGENT --rm -it \
	-p 0.0.0.0:$AGENT_PORT_RANGE:$AGENT_PORT_RANGE \
	$DOCKER_ENV \
	faber-alice-demo $AGENT_MODULE --port $AGENT_PORT $@
